apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: frontend
  template: #pod def
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: nginx-rs
        image: nginx