apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    course: devop
    trainer: "suresh"
  annotations:
    com.roboshop.com.durations: "120 hrs"
    jenklins.url: "hhtps://jenkins.com/roboshop/cataloogue#46"
spec:
  containers:
    - name: annotation
      image: mginx
      ports:
      - containerPort: 80