apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: envi-variabels
spec:
  containers:
  - name: environment-demo-container
    image: nginx
    env:
    - name: demo_greeting
      value: "ok thanks"
    - name: demo_farewall
      value: "no thanks"