apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
spec:
  - containers:
    name: configmap
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: course
      valueFrom:
        configMapKeyRef:
          name: devops-configmap
          key: course
    - name: trainer
      valueFrom:
        configMapKeyRef:
        name: devops-configmap
        key: trainer

