apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
  - name: configmap-pod
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: course
      valueFrom:
        configMapKeyRef:
          name: devops-configmap
          key: course
    - name: trainer
      valueFrom:
        configMapKeyRef:
          name: devops-configmap
          key: trainer

